### PR TITLE
Blogpost: Outreach Jan 2024

### PR DESCRIPTION
**Pull request by bjorgve**

### CODE REVIEW

**Comment by bast** [comment]
Thanks a lot for the write-up!
- Please reduce the size of the images for faster page load and slimmer Git repo
- The images don't show up in my local preview

**Comment by bjorgve** [comment]
Should be better now. Main problem is that I had added the "uncompressed" photos.

I also changed from jp2 to jpg, maybe that helps with the rendering.

**Comment by bast** [comment]
Thanks! Now one image renders. The other doesn't. Please try to preview it on your side.

**Comment by bjorgve** [comment]
Looks like I forgot to git add one of the images

**Comment by bast** [comment]
Thanks! And the persons on the photos are OK to be there? If yes, then ready to merge. Thank you again!

**Comment by Danzelot** [comment]
Okay from my side.

**Comment by bjorgve** [comment]
I've gotten the pictures approved. 

I don't have write access so I can't merge

**Comment by bast** [comment]
You just got an invite to a team/group. After accepting you can merge.

**Pull request merged**
