### PR TITLE
added recruit

### PR DESCRIPTION
**Pull request by tveitocc**
Added recruit, should be looked at by espen

### CODE REVIEW

**Comment by Danzelot** [comment]
Maybe a stupid question, since I wasn't part of the discussion but why is it called "recruit" (in the navigation) or "recruitment" (on the page itself)? Recruitment sounds more like we want to hire people than trying out resources.
Why was that name chosen?

**Comment by bast** [comment]
I was also very confused by that naming. This is not something users would identify with. The fact that we want to "recruit" users is our internal goal.

Suggestion for hopefully better naming: "computing-access"

**Comment by bast** [comment]
... or "access-to-computing" or "access" or ...?

**Comment by bast** [comment]
I have edited this some. Merging. Thanks again.

**Pull request merged**
